.\" Automatically generated by Pandoc 2.5
.\"
.TH "MSHELL" "1" "August 2021" "mshell 1.0.1" ""
.hy
.SH NAME
.PP
mshell \- a command line interpreter written in c
.SH SYNOPSIS
.PP
\f[B]mshell\f[R] [\f[I]filename\f[R]]
.SH DESCRIPTION
.PP
\f[B]mshell\f[R] is a custom shell interpreter that ships with a bunch
of great featu
.PD 0
.P
.PD
res that a local shell interpreter doesnot have.
when \f[B]mshell\f[R] is invoked wit
.PD 0
.P
.PD
h
.SS Invocation
.PP
\f[B]mshell\f[R] can be both invoked interractively or
non\-interractively if invoked with standard input not from terminal, it
can read commands from term inal
.PP
if invoked with standard input connected to the terminal, (determined by
isatty) , an interractive shell is opened
.PP
Alternatively, if a command line arg is provided, \f[B]mshell\f[R]
treats the first ar g as a file from which to read commands.
The supplied file should contain comman d per line
.SS Environment
.PP
Upon invocation, \f[B]mshell\f[R] copies the environment of the parent
process in whic h it was executed.This environment is an array of
name\-value strings in format o f NAME=VALUE.
.SS Command execution
.PP
After receiving command, \f[B]mshell\f[R] tokenizes it into words using
\f[B]\[dq] \[dq]\f[R] as a d elimiter, the first word as the command and
others are arguments.It then proceed s with the following action:
.PP
: if the first character of the command is neither a slash () nor dot
(.), the shell searches for it in the list of builtins.
.PP
: if the first char of the command is not ( \ or .
or builtins), the shell searc hes for it in the PATH environment var for
dir containing an executable file by that name
.PP
: if the search is successful it then executes the program in a separate
executi on environment
.SS Exit status
.PP
\f[B]mshell\f[R] returns the exit status of the last command executed
with zero indica ting success and a non\-zero for failure
.PP
if command is not found, return 127; if found but not executable return
127
.SS Signals
.PP
While running in interractive mode, \f[B]mshell\f[R] ignores keyboard **
ctrl + c ** .
Alternatively, an EOF input will exit program
.SS Variable replacement
.TP
.B \f[B]mshell\f[R] interprets $ character for variable replacement
\f[B]$ENV_VARIABLE\f[R] : ENV_VARIABLE is substituted with its value
\f[B]$?\f[R] : ?
is substituted with the return value of the last program
\f[B]$$\f[R] : $ is substituted the the current process id
.SS Comments
.PP
\f[B]mshell\f[R] ignores the all words and characters that preceeded by
a # char
.SS Operators
.PP
: ; \-Command separator: command separated by this operator are
processed sequen tially
.PP
: && \- and logical operator: command1 && command2 \- command2 is
executed if and only if, command1 returns a 0 exit status
.PP
: || \- or logical operator: command1 || command2 \- command2 is
executed even if command1 failed
.SS \f[B]mshell\f[R] Build in commands
.SS cd
.PP
\f[B]usage\f[R] :\f[B]cd\f[R] [DIRECTORY]
.PP
changed the current directory to DIRECTORY
.PP
if no arg provided the dir will be changed to dir in $HOME
.PP
if arg is ** \- \f[B], the command is interpreted as \f[R] cd $OLDPWD**
and the new working dir is printed
.PP
if arg is ** \[en] \f[B], the command is interpreted as \f[R] cd
$OLDPWD** and the new working dir is not printed
.PP
the PWD and OLDPWD env var are updated after changing dir
.SS alias
.PP
\f[B]usage\f[R] :\f[B]alias\f[R] [NAME=[`VALUE'] \&...].
Handles aliases
.PP
\f[B]alias\f[R] :prints all aliases in form of name\-value format
.PP
\f[B]alias\f[R] NAME \&...:prints aliases NAME and so on, in a
name\-value format
.PP
\f[B]alias\f[R] NAME=`VALUE':defines alias NAME
.SS exit
.PP
\f[B]usage\f[R] : \f[B]exit\f[R] [STATUS] Exits the shell.
if no status provided it is interpreted as ,\[lq]\f[B]exit\f[R] 0\[rq]
.SS env
.PP
prints current environment
.SS setenv
.PP
initializes new variable , or modifies the existing one.
.SS unsetenv
.PP
Removes the environment variable
.SH AUTHORS
mbuke prince and collins wilson.
